### PR TITLE
Make RISE to work with Jupyter master again

### LINKED ISSUE #46: display error on latest ipython master
Tried live_reveal against the latest ipython master, and the reveal slides get rendered into a tiny sliver instead of the full browser window. Reverting ipython to a commit from a few days back fixed it for me.

### PR DESCRIPTION
**Pull request by damianavila**
Fixes #46

It takes me a few hours to make it work despite the minimal changes... surgical fixes :wink:

pinging @twiecki and @mwiebe who are involved in the bug report...

Sorry to take to much time to fix it... master was really change it and now that 3.0 is coming soon is more stable to deal with...

### CODE REVIEW

**Comment by Zsailer** [comment]
Hey @damianavila ,

Tried this out today on the latest IPython/Jupyter master. The alignment isn't working for me (see screenshot below). The top of the slide starts outside of the window of view. 

Thanks for you work here! This extension is awesome for teaching!

live_reveal_ex

**Comment by damianavila** [comment]
Hey @Zsailer... nice to see you again... is there any possibility to share the notebook or some example notebook to see the behaviour, I can not reproduce it with my owns...

**Comment by Zsailer** [comment]
@damianavila nice to see you too!

I created a gist with the notebook from the screenshot above:
https://gist.github.com/Zsailer/e83f105357b0136b5c04

It's a pretty simple notebook... nothing unusual about it. I'll look at it tonight in more detail and confirm it's not coming from my custom.js/custom.css.

**Comment by damianavila** [comment]
>I'll look at it tonight in more detail and confirm it's not coming from my custom.js/custom.css.

Ahh... that could be the issue... I will check your notebook at night... thanks

**Comment by jhamrick** [comment]
I'm getting similar behavior, as of IPython master today. Here's what it looks like for me (I created a brand new notebook and just added a few cells to it):

image

And what the regular notebook looks like:

image

**Comment by damianavila** [comment]
OK... I will take a look... master change a little bit since I opened the PR... maybe something broke again...

**Comment by jhamrick** [comment]
Ok, I am investigating this a bit further (I'd like to use this for a lecture tomorrow, so I'll see if I can help fix it!) and part of the issue I think is some custom CSS I had. It's still not perfect, but better if I remove that.

**Comment by Zsailer** [comment]
I removed custom CSS and JS as well, and still get the exact same behavior. I'm a little swamped, so I haven't been able to look into this much. I did notice that slide element's `top` attribute is scaling to negative px values, but I couldn't identify the source of this in my short search..

**Comment by jhamrick** [comment]
Yes, that's what I'm finding, too -- pretty sure it has to do with the `top` attribute. I'll continue investigation as to why..

**Comment by jhamrick** [comment]
I think I figured it out! Here's a patch that makes it look correct:

```diff
From 62f8983c86d4569e9c28ada970002fabf7edda0e Mon Sep 17 00:00:00 2001
From: "Jessica B. Hamrick" <jhamrick@berkeley.edu>
Date: Mon, 26 Jan 2015 11:06:01 -0800
Subject: [PATCH] Make reveal work with new notebook layout

---
 livereveal/main.css         |  4 +++-
 livereveal/main.js          | 20 +++++++++++++-------
 livereveal/reset_reveal.css |  1 +
 3 files changed, 17 insertions(+), 8 deletions(-)

diff --git a/livereveal/main.css b/livereveal/main.css
index e1cfaba..e5b6aed 100644
--- a/livereveal/main.css
+++ b/livereveal/main.css
@@ -68,6 +68,9 @@
 div#notebook {
   overflow-x: hidden;
 }
+div#notebook.reveal {
+  padding-top: 0px;
+}
 div#notebook-container {
   background-color: transparent;
   -webkit-box-shadow: none;
@@ -99,4 +102,3 @@ div.output_subarea {
 html {
   overflow-y: auto;
 }
-
diff --git a/livereveal/main.js b/livereveal/main.js
index f9191b5..9f370c5 100644
--- a/livereveal/main.js
+++ b/livereveal/main.js
@@ -125,14 +125,14 @@ function labelIntraSlides(){
 
 function Slider(begin, end, container) {
   // Hiding header and the toolbar
-  $('div#header-container').toggle();
+  $('div#header').toggle();
   $('div#maintoolbar').toggle();
   IPython.menubar._size_header();
   //if(event)event.preventDefault();
 
   // switch the panel back color to white (it does not work in css,
   // I do not why, so switching by js)
-  $('div#notebook_panel').css('background-color','#ffffff');
+  $('div#site').css('background-color','#ffffff');
 
   /*
    * The crazy rearrangement, I read the following some months ago,
@@ -191,6 +191,8 @@ function Slider(begin, end, container) {
 
 function Revealer(ttheme, ttransition){
   // Bodier
+  $('div#site').css("height", "100%");  
+  $('div#ipython-main-app').css("position", "static");
   $('div#notebook').addClass("reveal");
   $('div#notebook-container').addClass("slides");
 
@@ -249,6 +251,7 @@ function Revealer(ttheme, ttransition){
     Reveal.addEventListener( 'ready', function( event ) {
       Unselecter();
       IPython.notebook.scroll_to_top();
+      Reveal.layout();
     });
 
     Reveal.addEventListener( 'slidechanged', function( event ) {
@@ -336,7 +339,7 @@ function buttonExit() {
         .addClass(exit_icon)
         .addClass('my-main-tool-bar')
         .css('position','fixed')
-        .css('top','1.0em')
+        .css('top','0.5em')
         .css('left','0.48em')
         .css('opacity', '0.6')
         .click(
@@ -348,15 +351,18 @@ function buttonExit() {
 }
 
 function Remover() {
-  $('div#notebook_panel').css('background-color','#ffffff');
-  $('div#header-container').toggle();
+  $('div#site').css("height", "");  
+  $('div#site').css('background-color','');
+  $("div#ipython-main-app").css("position", "");
+  $('div#header').toggle();
   $('div#maintoolbar').toggle();
   IPython.menubar._size_header();
 
   $('div#notebook').removeClass("reveal");
   $('div#notebook-container').removeClass("slides");
-  $('div#notebook-container').css('width','1140px');
-  $('div#notebook-container').css('height','inherit');
+  $('div#notebook-container').css('width','');
+  $('div#notebook-container').css('height','');
+  $('div#notebook-container').css('zoom','');
 
   $('#maincss').remove();
   $('#theme').remove();
diff --git a/livereveal/reset_reveal.css b/livereveal/reset_reveal.css
index 013012b..265ca4a 100644
--- a/livereveal/reset_reveal.css
+++ b/livereveal/reset_reveal.css
@@ -79,6 +79,7 @@ body {
 
 	word-wrap: break-word;
 	line-height: 1;
+	margin-top: 0px !important;
 }
 
 .reveal h1 { font-size: 3.77em; }
-- 
2.2.1
```

**Comment by damianavila** [comment]
Thanks @jhamrick to look deeper into this... would you like to submit the patch against this PR? You solved it and you deserved the credit... so if you have some time, please just push the fix to my PR so I can merge it and then merge this PR to master... thanks!!!

**Comment by Zsailer** [comment]
@jhamrick @damianavila  Nice! The patch worked for me. Thanks!

**Comment by damianavila** [comment]
@jhamrick, I merge your patch and still I am seeing weird things... can you give more info about your IPython.sys_info and the browser (and version) you are using? I am starting to think there is something broken across multiple browser version... thanks!

**Comment by damianavila** [comment]
OK, I testes this with somewhat 3.0 beta and it work well with some minor fixes to do... I will merge this one and solve the tiny issues in specific PRs. Thanks everyone!!

**Pull request merged**
